package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlunoSimulado generated by hbm2java
 */
@Entity
@Table(name="aluno_simulado"
    ,catalog="kemdixip_sgedanovo"
)
public class AlunoSimulado  implements java.io.Serializable {


     private AlunoSimuladoId id;
     private Aluno aluno;
     private Simulado simulado;
     private Date data;
     private Set<Resposta> respostas = new HashSet(0);

    public AlunoSimulado() {
    }

	
    public AlunoSimulado(AlunoSimuladoId id, Aluno aluno, Simulado simulado) {
        this.id = id;
        this.aluno = aluno;
        this.simulado = simulado;
    }
    public AlunoSimulado(AlunoSimuladoId id, Aluno aluno, Simulado simulado, Date data, Set<Resposta> respostas) {
       this.id = id;
       this.aluno = aluno;
       this.simulado = simulado;
       this.data = data;
       this.respostas = respostas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alunoIdAluno", column=@Column(name="aluno_idAluno", nullable=false) ), 
        @AttributeOverride(name="simuladoIdSimulado", column=@Column(name="simulado_idSimulado", nullable=false) ) } )
    public AlunoSimuladoId getId() {
        return this.id;
    }
    
    public void setId(AlunoSimuladoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aluno_idAluno", nullable=false, insertable=false, updatable=false)
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="simulado_idSimulado", nullable=false, insertable=false, updatable=false)
    public Simulado getSimulado() {
        return this.simulado;
    }
    
    public void setSimulado(Simulado simulado) {
        this.simulado = simulado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="alunoSimulado")
    public Set<Resposta> getRespostas() {
        return this.respostas;
    }
    
    public void setRespostas(Set<Resposta> respostas) {
        this.respostas = respostas;
    }




}


