package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlunoHasSimuladoId generated by hbm2java
 */
@Embeddable
public class AlunoHasSimuladoId  implements java.io.Serializable {


     private int alunoIdAluno;
     private int simuladoIdSimulado;

    public AlunoHasSimuladoId() {
    }

    public AlunoHasSimuladoId(int alunoIdAluno, int simuladoIdSimulado) {
       this.alunoIdAluno = alunoIdAluno;
       this.simuladoIdSimulado = simuladoIdSimulado;
    }
   


    @Column(name="aluno_idAluno", nullable=false)
    public int getAlunoIdAluno() {
        return this.alunoIdAluno;
    }
    
    public void setAlunoIdAluno(int alunoIdAluno) {
        this.alunoIdAluno = alunoIdAluno;
    }


    @Column(name="simulado_idSimulado", nullable=false)
    public int getSimuladoIdSimulado() {
        return this.simuladoIdSimulado;
    }
    
    public void setSimuladoIdSimulado(int simuladoIdSimulado) {
        this.simuladoIdSimulado = simuladoIdSimulado;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlunoHasSimuladoId) ) return false;
		 AlunoHasSimuladoId castOther = ( AlunoHasSimuladoId ) other; 
         
		 return (this.getAlunoIdAluno()==castOther.getAlunoIdAluno())
 && (this.getSimuladoIdSimulado()==castOther.getSimuladoIdSimulado());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlunoIdAluno();
         result = 37 * result + this.getSimuladoIdSimulado();
         return result;
   }   


}


