package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AlunoSimulado generated by hbm2java
 */
@Entity
@Table(name="aluno_simulado"
    ,catalog="kemdixip_sgedanovo"
)
public class AlunoSimulado  implements java.io.Serializable {


     private AlunoSimuladoId id;
     private Aluno aluno;
     private TurmaSimulado turmaSimulado;
     private Date data;
     private List<Resposta> respostas = new ArrayList<>(0);

    public AlunoSimulado() {
    }

	
    public AlunoSimulado(AlunoSimuladoId id, Aluno aluno, TurmaSimulado simulado) {
        this.id = id;
        this.aluno = aluno;
        this.turmaSimulado = simulado;
    }
    public AlunoSimulado(AlunoSimuladoId id, Aluno aluno, TurmaSimulado simulado, Date data, List<Resposta> respostas) {
       this.id = id;
       this.aluno = aluno;
       this.turmaSimulado = simulado;
       this.data = data;
       this.respostas = respostas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alunoIdAluno", column=@Column(name="aluno_idAluno", nullable=false) ), 
        @AttributeOverride(name="simuladoIdSimulado", column=@Column(name="simulado_idSimulado", nullable=false) ), 
        @AttributeOverride(name="turmaIdTurma", column=@Column(name="turma_idTurma", nullable=false) ) } )
    public AlunoSimuladoId getId() {
        return this.id;
    }
    
    public void setId(AlunoSimuladoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="aluno_idAluno", nullable=false, insertable=false, updatable=false)
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumns( {  
        @JoinColumn(name="simulado_idSimulado", referencedColumnName="simulado_idSimulado", nullable=false, insertable=false, updatable=false),
        @JoinColumn(name="turma_idTurma", referencedColumnName="turma_idTurma", nullable=false, insertable=false, updatable=false)} )
    public TurmaSimulado getTurmaSimulado() {
        return this.turmaSimulado;
    }
    
    public void setTurmaSimulado(TurmaSimulado turmaSimulado) {
        this.turmaSimulado = turmaSimulado;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="data", length=19)
    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

@OneToMany(fetch=FetchType.EAGER, mappedBy="alunoSimulado")
    public List<Resposta> getRespostas() {
        return this.respostas;
    }
    
    public void setRespostas(List<Resposta> respostas) {
        this.respostas = respostas;
    }




}


