package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Aluno generated by hbm2java
 */
@Entity
@Table(name="aluno"
    ,catalog="kemdixip_sgeda"
)
public class Aluno  implements java.io.Serializable {


     private int idAluno;
     private Pessoa pessoa;
     private String nomeResponsavel;
     private String escolaridade;
     private String cpfResponsavel;
     private String telefoneResponsavel;
     private Set<TurmaAluno> turmaAlunos = new HashSet(0);
     private Set<AlunoSimulado> alunoSimulados = new HashSet(0);

    public Aluno() {
    }

	
    public Aluno(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Aluno(Pessoa pessoa, String nomeResponsavel, String escolaridade, String cpfResponsavel, String telefoneResponsavel, Set<TurmaAluno> turmaAlunos, Set<AlunoSimulado> alunoSimulados) {
       this.pessoa = pessoa;
       this.nomeResponsavel = nomeResponsavel;
       this.escolaridade = escolaridade;
       this.cpfResponsavel = cpfResponsavel;
       this.telefoneResponsavel = telefoneResponsavel;
       this.turmaAlunos = turmaAlunos;
       this.alunoSimulados = alunoSimulados;
    }
   
    @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pessoa"))
    @Id @GeneratedValue(generator="generator")
    @Column(name="idAluno", unique=true, nullable=false)
    public int getIdAluno() {
        return this.idAluno;
    }
    
    public void setIdAluno(int idAluno) {
        this.idAluno = idAluno;
    }

    @OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="nomeResponsavel")
    public String getNomeResponsavel() {
        return this.nomeResponsavel;
    }
    
    public void setNomeResponsavel(String nomeResponsavel) {
        this.nomeResponsavel = nomeResponsavel;
    }

    
    @Column(name="escolaridade", length=50)
    public String getEscolaridade() {
        return this.escolaridade;
    }
    
    public void setEscolaridade(String escolaridade) {
        this.escolaridade = escolaridade;
    }

    
    @Column(name="cpfResponsavel", length=11)
    public String getCpfResponsavel() {
        return this.cpfResponsavel;
    }
    
    public void setCpfResponsavel(String cpfResponsavel) {
        this.cpfResponsavel = cpfResponsavel;
    }

    
    @Column(name="telefoneResponsavel", length=11)
    public String getTelefoneResponsavel() {
        return this.telefoneResponsavel;
    }
    
    public void setTelefoneResponsavel(String telefoneResponsavel) {
        this.telefoneResponsavel = telefoneResponsavel;
    }

    @OneToMany(fetch=FetchType.EAGER, mappedBy="aluno")
    public Set<TurmaAluno> getTurmaAlunos() {
        return this.turmaAlunos;
    }
    
    public void setTurmaAlunos(Set<TurmaAluno> turmaAlunos) {
        this.turmaAlunos = turmaAlunos;
    }

    @OneToMany(fetch=FetchType.LAZY, mappedBy="aluno")
    public Set<AlunoSimulado> getAlunoSimulados() {
        return this.alunoSimulados;
    }
    
    public void setAlunoSimulados(Set<AlunoSimulado> alunoSimulados) {
        this.alunoSimulados = alunoSimulados;
    }




}


