package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AlunoHasTurmaId generated by hbm2java
 */
@Embeddable
public class AlunoHasTurmaId  implements java.io.Serializable {


     private int alunoIdAluno;
     private int turmaIdTurma;
     private int turmaIdDisciplina;

    public AlunoHasTurmaId() {
    }

    public AlunoHasTurmaId(int alunoIdAluno, int turmaIdTurma, int turmaIdDisciplina) {
       this.alunoIdAluno = alunoIdAluno;
       this.turmaIdTurma = turmaIdTurma;
       this.turmaIdDisciplina = turmaIdDisciplina;
    }
   


    @Column(name="aluno_idAluno", nullable=false)
    public int getAlunoIdAluno() {
        return this.alunoIdAluno;
    }
    
    public void setAlunoIdAluno(int alunoIdAluno) {
        this.alunoIdAluno = alunoIdAluno;
    }


    @Column(name="turma_idTurma", nullable=false)
    public int getTurmaIdTurma() {
        return this.turmaIdTurma;
    }
    
    public void setTurmaIdTurma(int turmaIdTurma) {
        this.turmaIdTurma = turmaIdTurma;
    }


    @Column(name="turma_idDisciplina", nullable=false)
    public int getTurmaIdDisciplina() {
        return this.turmaIdDisciplina;
    }
    
    public void setTurmaIdDisciplina(int turmaIdDisciplina) {
        this.turmaIdDisciplina = turmaIdDisciplina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AlunoHasTurmaId) ) return false;
		 AlunoHasTurmaId castOther = ( AlunoHasTurmaId ) other; 
         
		 return (this.getAlunoIdAluno()==castOther.getAlunoIdAluno())
 && (this.getTurmaIdTurma()==castOther.getTurmaIdTurma())
 && (this.getTurmaIdDisciplina()==castOther.getTurmaIdDisciplina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlunoIdAluno();
         result = 37 * result + this.getTurmaIdTurma();
         result = 37 * result + this.getTurmaIdDisciplina();
         return result;
   }   


}


