package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Disciplina generated by hbm2java
 */
@Entity
@Table(name="disciplina"
    ,catalog="sgeda"
)
public class Disciplina  implements java.io.Serializable {


     private Integer idDisciplina;
     private String nome;
     private String descricao;
     private Set<Subdisciplina> subdisciplinas;

    public Disciplina() {
    }

    public Disciplina(String nome, String descricao, Set subdisciplinas, Set cursos, Set turmas, Set professors, Set questaos) {
       this.nome = nome;
       this.descricao = descricao;
       this.subdisciplinas = subdisciplinas;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idDisciplina", unique=true, nullable=false)
    public Integer getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(Integer idDisciplina) {
        this.idDisciplina = idDisciplina;
    }

    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="disciplina")
    public Set<Subdisciplina> getSubdisciplinas() {
        return this.subdisciplinas;
    }
    
    public void setSubdisciplinas(Set subdisciplinas) {
        this.subdisciplinas = subdisciplinas;
    }

}
