package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Discursiva generated by hbm2java
 */
@Entity
@Table(name="discursiva"
    ,catalog="sgeda"
)
public class Discursiva  implements java.io.Serializable {


     private int idDiscursiva;
     private Questao questao;
     private String respostaPadrao;

    public Discursiva() {
    }

	
    public Discursiva(Questao questao) {
        this.questao = questao;
    }
    public Discursiva(Questao questao, String respostaPadrao) {
       this.questao = questao;
       this.respostaPadrao = respostaPadrao;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="questao"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idDiscursiva", unique=true, nullable=false)
    public int getIdDiscursiva() {
        return this.idDiscursiva;
    }
    
    public void setIdDiscursiva(int idDiscursiva) {
        this.idDiscursiva = idDiscursiva;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Questao getQuestao() {
        return this.questao;
    }
    
    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

    
    @Column(name="respostaPadrao", length=1500)
    public String getRespostaPadrao() {
        return this.respostaPadrao;
    }
    
    public void setRespostaPadrao(String respostaPadrao) {
        this.respostaPadrao = respostaPadrao;
    }




}


