package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Endereco generated by hbm2java
 */
@Entity
@Table(name="endereco"
    ,catalog="kemdixip_sgedanovo"
)
public class Endereco  implements java.io.Serializable {


     private Integer idEndereco;
     private Pessoa pessoa;
     private String logradouro;
     private String numero;
     private String complemento;
     private String cep;
     private String bairro;
     private String cidade;
     private String estado;

    public Endereco() {
    }

	
    public Endereco(Pessoa pessoa, String cep) {
        this.pessoa = pessoa;
        this.cep = cep;
    }
    public Endereco(Pessoa pessoa, String logradouro, String numero, String complemento, String cep, String bairro, String cidade, String estado) {
       this.pessoa = pessoa;
       this.logradouro = logradouro;
       this.numero = numero;
       this.complemento = complemento;
       this.cep = cep;
       this.bairro = bairro;
       this.cidade = cidade;
       this.estado = estado;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEndereco", unique=true, nullable=false)
    public Integer getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(Integer idEndereco) {
        this.idEndereco = idEndereco;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPessoa", nullable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="logradouro")
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    
    @Column(name="numero", length=50)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }

    
    @Column(name="complemento")
    public String getComplemento() {
        return this.complemento;
    }
    
    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    
    @Column(name="cep", nullable=false, length=8)
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }

    
    @Column(name="bairro", length=50)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="cidade", length=50)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="estado", length=2)
    public String getEstado() {
        return this.estado;
    }
    
    public void setEstado(String estado) {
        this.estado = estado;
    }




}


