package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EnderecoId generated by hbm2java
 */
@Embeddable
public class EnderecoId  implements java.io.Serializable {


     private int idEndereco;
     private int idPessoa;

    public EnderecoId() {
    }

    public EnderecoId(int idEndereco, int idPessoa) {
       this.idEndereco = idEndereco;
       this.idPessoa = idPessoa;
    }
   


    @Column(name="idEndereco", nullable=false)
    public int getIdEndereco() {
        return this.idEndereco;
    }
    
    public void setIdEndereco(int idEndereco) {
        this.idEndereco = idEndereco;
    }


    @Column(name="idPessoa", nullable=false)
    public int getIdPessoa() {
        return this.idPessoa;
    }
    
    public void setIdPessoa(int idPessoa) {
        this.idPessoa = idPessoa;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EnderecoId) ) return false;
		 EnderecoId castOther = ( EnderecoId ) other; 
         
		 return (this.getIdEndereco()==castOther.getIdEndereco())
 && (this.getIdPessoa()==castOther.getIdPessoa());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdEndereco();
         result = 37 * result + this.getIdPessoa();
         return result;
   }   


}


