package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Enunciadogrupo generated by hbm2java
 */
@Entity
@Table(name="enunciadogrupo"
    ,catalog="sgeda"
)
public class Enunciadogrupo  implements java.io.Serializable {


     private Integer idEnunciadoGrupo;
     private String enunciado;
     private Set questaos = new HashSet(0);

    public Enunciadogrupo() {
    }

    public Enunciadogrupo(String enunciado, Set questaos) {
       this.enunciado = enunciado;
       this.questaos = questaos;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idEnunciadoGrupo", unique=true, nullable=false)
    public Integer getIdEnunciadoGrupo() {
        return this.idEnunciadoGrupo;
    }
    
    public void setIdEnunciadoGrupo(Integer idEnunciadoGrupo) {
        this.idEnunciadoGrupo = idEnunciadoGrupo;
    }

    
    @Column(name="enunciado", length=3000)
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="enunciadogrupo")
    public Set getQuestaos() {
        return this.questaos;
    }
    
    public void setQuestaos(Set questaos) {
        this.questaos = questaos;
    }




}


