package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FiguraId generated by hbm2java
 */
@Embeddable
public class FiguraId  implements java.io.Serializable {


     private int idFigura;
     private int idQuestao;

    public FiguraId() {
    }

    public FiguraId(int idFigura, int idQuestao) {
       this.idFigura = idFigura;
       this.idQuestao = idQuestao;
    }
   


    @Column(name="idFigura", nullable=false)
    public int getIdFigura() {
        return this.idFigura;
    }
    
    public void setIdFigura(int idFigura) {
        this.idFigura = idFigura;
    }


    @Column(name="idQuestao", nullable=false)
    public int getIdQuestao() {
        return this.idQuestao;
    }
    
    public void setIdQuestao(int idQuestao) {
        this.idQuestao = idQuestao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FiguraId) ) return false;
		 FiguraId castOther = ( FiguraId ) other; 
         
		 return (this.getIdFigura()==castOther.getIdFigura())
 && (this.getIdQuestao()==castOther.getIdQuestao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdFigura();
         result = 37 * result + this.getIdQuestao();
         return result;
   }   


}


