package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Figura generated by hbm2java
 */
@Entity
@Table(name="figura"
    ,catalog="sgeda"
)
public class Figura  implements java.io.Serializable {


     private FiguraId id;
     private Questao questao;
     private String nome;
     private String descricao;
     private String tamanho;
     private String tipo;
     private byte[] imagem;

    public Figura() {
    }

	
    public Figura(FiguraId id, Questao questao) {
        this.id = id;
        this.questao = questao;
    }
    public Figura(FiguraId id, Questao questao, String nome, String descricao, String tamanho, String tipo, byte[] imagem) {
       this.id = id;
       this.questao = questao;
       this.nome = nome;
       this.descricao = descricao;
       this.tamanho = tamanho;
       this.tipo = tipo;
       this.imagem = imagem;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idFigura", column=@Column(name="idFigura", nullable=false) ), 
        @AttributeOverride(name="idQuestao", column=@Column(name="idQuestao", nullable=false) ) } )
    public FiguraId getId() {
        return this.id;
    }
    
    public void setId(FiguraId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idQuestao", nullable=false, insertable=false, updatable=false)
    public Questao getQuestao() {
        return this.questao;
    }
    
    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

    
    @Column(name="nome", length=25)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="tamanho", length=25)
    public String getTamanho() {
        return this.tamanho;
    }
    
    public void setTamanho(String tamanho) {
        this.tamanho = tamanho;
    }

    
    @Column(name="tipo", length=25)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="imagem")
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }




}


