package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Figura generated by hbm2java
 */
@Entity
@Table(name="foto"
    ,catalog="kemdixip_sgedanovo"
)
public class Foto  implements java.io.Serializable {


    private Integer idFoto;
    private String tamanho;
    private String tipo;
    private byte[] imagem;
    private Pessoa pessoa;
    
    public Foto() {
    }

    public Foto(String tamanho, String tipo, byte[] imagem) {
       this.tamanho = tamanho;
       this.tipo = tipo;
       this.imagem = imagem;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFoto", unique=true, nullable=false)
    public Integer getIdFoto() {
        return this.idFoto;
    }
    
    public void setIdFoto(Integer idFoto) {
        this.idFoto = idFoto;
    }

    @Column(name="tamanho", length=45)
    public String getTamanho() {
        return this.tamanho;
    }
    
    public void setTamanho(String tamanho) {
        this.tamanho = tamanho;
    }

    
    @Column(name="tipo", length=45)
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    
    @Column(name="imagem")
    public byte[] getImagem() {
        return this.imagem;
    }
    
    public void setImagem(byte[] imagem) {
        this.imagem = imagem;
    }

    @OneToOne(fetch=FetchType.LAZY, mappedBy="foto")
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
}


