package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Opcao generated by hbm2java
 */
@Entity
@Table(name="opcao"
    ,catalog="sgeda"
)
public class Opcao  implements java.io.Serializable {


     private Integer idOpcao;
     private Objetiva objetiva;
     private Character opcao;
     private String descricao;
     private Boolean correta;

    public Opcao() {
    }

	
    public Opcao(Objetiva objetiva) {
        this.objetiva = objetiva;
    }
    public Opcao(Objetiva objetiva, Character opcao, String descricao, Boolean correta) {
       this.objetiva = objetiva;
       this.opcao = opcao;
       this.descricao = descricao;
       this.correta = correta;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idOpcao", unique=true, nullable=false)
    public Integer getIdOpcao() {
        return this.idOpcao;
    }
    
    public void setIdOpcao(Integer idOpcao) {
        this.idOpcao = idOpcao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idObjetiva", nullable=false)
    public Objetiva getObjetiva() {
        return this.objetiva;
    }
    
    public void setObjetiva(Objetiva objetiva) {
        this.objetiva = objetiva;
    }

    
    @Column(name="opcao", length=1)
    public Character getOpcao() {
        return this.opcao;
    }
    
    public void setOpcao(Character opcao) {
        this.opcao = opcao;
    }

    
    @Column(name="descricao", length=1500)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="correta")
    public Boolean getCorreta() {
        return this.correta;
    }
    
    public void setCorreta(Boolean correta) {
        this.correta = correta;
    }




}


