package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Transient;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Professor generated by hbm2java
 */
@Entity
@Table(name="professor"
    ,catalog="kemdixip_sgedanovo"
)
public class Professor  implements java.io.Serializable {


     private int idProfessor;
     private Pessoa pessoa;
     private String especializacao;
     private String intituicaoFormacao;
     private Set<Disciplina> disciplinas = new HashSet(0);
     private Set<Turma> turmas = new HashSet(0);
     private Set<Simulado> simulados = new HashSet(0);
     private Set<Questao> questaos = new HashSet(0);

    public Professor() {
    }

	
    public Professor(Pessoa pessoa) {
        this.pessoa = pessoa;
    }
    public Professor(Pessoa pessoa, String especializacao, String intituicaoFormacao, Set<Disciplina> disciplinas, Set<Turma> turmas, Set<Simulado> simulados, Set<Questao> questaos) {
       this.pessoa = pessoa;
       this.especializacao = especializacao;
       this.intituicaoFormacao = intituicaoFormacao;
       this.disciplinas = disciplinas;
       this.turmas = turmas;
       this.simulados = simulados;
       this.questaos = questaos;
    }
    
    public Professor(Pessoa pessoa, String especializacao, String intituicaoFormacao, Set<Disciplina> disciplinas) {
       this.pessoa = pessoa;
       this.especializacao = especializacao;
       this.intituicaoFormacao = intituicaoFormacao;
       this.disciplinas = disciplinas;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="pessoa"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idProfessor", unique=true, nullable=false)
    public int getIdProfessor() {
        return this.idProfessor;
    }
    
    public void setIdProfessor(int idProfessor) {
        this.idProfessor = idProfessor;
    }

@OneToOne(fetch=FetchType.EAGER)@PrimaryKeyJoinColumn
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="especializacao", length=100)
    public String getEspecializacao() {
        return this.especializacao;
    }
    
    public void setEspecializacao(String especializacao) {
        this.especializacao = especializacao;
    }

    
    @Column(name="intituicaoFormacao", length=100)
    public String getIntituicaoFormacao() {
        return this.intituicaoFormacao;
    }
    
    public void setIntituicaoFormacao(String intituicaoFormacao) {
        this.intituicaoFormacao = intituicaoFormacao;
    }

@ManyToMany(fetch=FetchType.EAGER)
    @JoinTable(name="professor_habilitado_disciplina", catalog="kemdixip_sgedanovo", joinColumns = { 
        @JoinColumn(name="professor_idProfessor", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="disciplina_idDisciplina", nullable=false, updatable=false) })
    public Set<Disciplina> getDisciplinas() {
        return this.disciplinas;
    }
    
    public void setDisciplinas(Set<Disciplina> disciplinas) {
        this.disciplinas = disciplinas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professor")
    public Set<Turma> getTurmas() {
        return this.turmas;
    }
    
    public void setTurmas(Set<Turma> turmas) {
        this.turmas = turmas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professor")
    public Set<Simulado> getSimulados() {
        return this.simulados;
    }
    
    public void setSimulados(Set<Simulado> simulados) {
        this.simulados = simulados;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="professor")
    public Set<Questao> getQuestaos() {
        return this.questaos;
    }
    
    public void setQuestaos(Set<Questao> questaos) {
        this.questaos = questaos;
    }

}


