package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OneToOne;
import javax.persistence.Table;

/**
 * Questao generated by hbm2java
 */
@Entity
@Table(name="questao"
    ,catalog="sgeda"
)
public class Questao  implements java.io.Serializable {


     private Integer idQuestao;
     private Enunciadogrupo enunciadogrupo;
     private Professor professor;
     private Subdisciplina subdisciplina;
     private String enunciado;
     private String ano;
     private String instituicao;
     private Set<Figura> figuras = new HashSet(0);

    public Questao() {
    }

	
    public Questao(Professor professor, Subdisciplina subdisciplina) {
        this.professor = professor;
        this.subdisciplina = subdisciplina;
    }
    public Questao(Enunciadogrupo enunciadogrupo, Professor professor, Subdisciplina subdisciplina, String enunciado, String ano, String instituicao, Discursiva discursiva, Set<Figura> figuras) {
       this.enunciadogrupo = enunciadogrupo;
       this.professor = professor;
       this.subdisciplina = subdisciplina;
       this.enunciado = enunciado;
       this.ano = ano;
       this.instituicao = instituicao;
       this.figuras = figuras;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idQuestao", unique=true, nullable=false)
    public Integer getIdQuestao() {
        return this.idQuestao;
    }
    
    public void setIdQuestao(Integer idQuestao) {
        this.idQuestao = idQuestao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idEnunciadoGrupo")
    public Enunciadogrupo getEnunciadogrupo() {
        return this.enunciadogrupo;
    }
    
    public void setEnunciadogrupo(Enunciadogrupo enunciadogrupo) {
        this.enunciadogrupo = enunciadogrupo;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProfessor", nullable=false)
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumns( { 
        @JoinColumn(name="idSubdisciplina", referencedColumnName="idSubdisciplina", nullable=false), 
        @JoinColumn(name="idDisciplina", referencedColumnName="idDisciplina", nullable=false) } )
    public Subdisciplina getSubdisciplina() {
        return this.subdisciplina;
    }
    
    public void setSubdisciplina(Subdisciplina subdisciplina) {
        this.subdisciplina = subdisciplina;
    }

    
    @Column(name="enunciado", length=1500)
    public String getEnunciado() {
        return this.enunciado;
    }
    
    public void setEnunciado(String enunciado) {
        this.enunciado = enunciado;
    }

    
    @Column(name="ano", length=4)
    public String getAno() {
        return this.ano;
    }
    
    public void setAno(String ano) {
        this.ano = ano;
    }

    
    @Column(name="instituicao", length=10)
    public String getInstituicao() {
        return this.instituicao;
    }
    
    public void setInstituicao(String instituicao) {
        this.instituicao = instituicao;
    }


@OneToMany(fetch=FetchType.LAZY, mappedBy="questao")
    public Set<Figura> getFiguras() {
        return this.figuras;
    }
    
    public void setFiguras(Set<Figura> figuras) {
        this.figuras = figuras;
    }

}


