package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Redacao generated by hbm2java
 */
@Entity
@Table(name="redacao"
    ,catalog="sgeda"
)
public class Redacao  implements java.io.Serializable {


     private int idRedacao;
     private Questao questao;
     private Integer qntLinhas;

    public Redacao() {
    }

	
    public Redacao(Questao questao) {
        this.questao = questao;
    }
    public Redacao(Questao questao, Integer qntLinhas) {
       this.questao = questao;
       this.qntLinhas = qntLinhas;
    }
   
     @GenericGenerator(name="generator", strategy="foreign", parameters=@Parameter(name="property", value="questao"))@Id @GeneratedValue(generator="generator")

    
    @Column(name="idRedacao", unique=true, nullable=false)
    public int getIdRedacao() {
        return this.idRedacao;
    }
    
    public void setIdRedacao(int idRedacao) {
        this.idRedacao = idRedacao;
    }

@OneToOne(fetch=FetchType.LAZY)@PrimaryKeyJoinColumn
    public Questao getQuestao() {
        return this.questao;
    }
    
    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

    
    @Column(name="qntLinhas")
    public Integer getQntLinhas() {
        return this.qntLinhas;
    }
    
    public void setQntLinhas(Integer qntLinhas) {
        this.qntLinhas = qntLinhas;
    }




}


