package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * SimuladoHasQuestao generated by hbm2java
 */
@Entity
@Table(name="simulado_has_questao"
    ,catalog="sgeda"
)
public class SimuladoHasQuestao  implements java.io.Serializable {


     private SimuladoHasQuestaoId id;
     private Questao questao;
     private Simulado simulado;
     private BigDecimal valorQuestao;

    public SimuladoHasQuestao() {
    }

	
    public SimuladoHasQuestao(SimuladoHasQuestaoId id, Questao questao, Simulado simulado) {
        this.id = id;
        this.questao = questao;
        this.simulado = simulado;
    }
    public SimuladoHasQuestao(SimuladoHasQuestaoId id, Questao questao, Simulado simulado, BigDecimal valorQuestao) {
       this.id = id;
       this.questao = questao;
       this.simulado = simulado;
       this.valorQuestao = valorQuestao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="simuladoIdSimulado", column=@Column(name="simulado_idSimulado", nullable=false) ), 
        @AttributeOverride(name="questaoIdQuestao", column=@Column(name="questao_idQuestao", nullable=false) ) } )
    public SimuladoHasQuestaoId getId() {
        return this.id;
    }
    
    public void setId(SimuladoHasQuestaoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="questao_idQuestao", nullable=false, insertable=false, updatable=false)
    public Questao getQuestao() {
        return this.questao;
    }
    
    public void setQuestao(Questao questao) {
        this.questao = questao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="simulado_idSimulado", nullable=false, insertable=false, updatable=false)
    public Simulado getSimulado() {
        return this.simulado;
    }
    
    public void setSimulado(Simulado simulado) {
        this.simulado = simulado;
    }

    
    @Column(name="valorQuestao", precision=5)
    public BigDecimal getValorQuestao() {
        return this.valorQuestao;
    }
    
    public void setValorQuestao(BigDecimal valorQuestao) {
        this.valorQuestao = valorQuestao;
    }




}


