package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SimuladoQuestaoId generated by hbm2java
 */
@Embeddable
public class SimuladoQuestaoId  implements java.io.Serializable {


     private int simuladoIdSimulado;
     private int questaoIdQuestao;

    public SimuladoQuestaoId() {
    }

    public SimuladoQuestaoId(int simuladoIdSimulado, int questaoIdQuestao) {
       this.simuladoIdSimulado = simuladoIdSimulado;
       this.questaoIdQuestao = questaoIdQuestao;
    }
   


    @Column(name="simulado_idSimulado", nullable=false)
    public int getSimuladoIdSimulado() {
        return this.simuladoIdSimulado;
    }
    
    public void setSimuladoIdSimulado(int simuladoIdSimulado) {
        this.simuladoIdSimulado = simuladoIdSimulado;
    }


    @Column(name="questao_idQuestao", nullable=false)
    public int getQuestaoIdQuestao() {
        return this.questaoIdQuestao;
    }
    
    public void setQuestaoIdQuestao(int questaoIdQuestao) {
        this.questaoIdQuestao = questaoIdQuestao;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SimuladoQuestaoId) ) return false;
		 SimuladoQuestaoId castOther = ( SimuladoQuestaoId ) other; 
         
		 return (this.getSimuladoIdSimulado()==castOther.getSimuladoIdSimulado())
 && (this.getQuestaoIdQuestao()==castOther.getQuestaoIdQuestao());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSimuladoIdSimulado();
         result = 37 * result + this.getQuestaoIdQuestao();
         return result;
   }   


}


