package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SimuladoHasTurmaId generated by hbm2java
 */
@Embeddable
public class SimuladoHasTurmaId  implements java.io.Serializable {


     private int simuladoIdSimulado;
     private int turmaIdTurma;
     private int turmaIdDisciplina;

    public SimuladoHasTurmaId() {
    }

    public SimuladoHasTurmaId(int simuladoIdSimulado, int turmaIdTurma, int turmaIdDisciplina) {
       this.simuladoIdSimulado = simuladoIdSimulado;
       this.turmaIdTurma = turmaIdTurma;
       this.turmaIdDisciplina = turmaIdDisciplina;
    }
   


    @Column(name="simulado_idSimulado", nullable=false)
    public int getSimuladoIdSimulado() {
        return this.simuladoIdSimulado;
    }
    
    public void setSimuladoIdSimulado(int simuladoIdSimulado) {
        this.simuladoIdSimulado = simuladoIdSimulado;
    }


    @Column(name="turma_idTurma", nullable=false)
    public int getTurmaIdTurma() {
        return this.turmaIdTurma;
    }
    
    public void setTurmaIdTurma(int turmaIdTurma) {
        this.turmaIdTurma = turmaIdTurma;
    }


    @Column(name="turma_idDisciplina", nullable=false)
    public int getTurmaIdDisciplina() {
        return this.turmaIdDisciplina;
    }
    
    public void setTurmaIdDisciplina(int turmaIdDisciplina) {
        this.turmaIdDisciplina = turmaIdDisciplina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SimuladoHasTurmaId) ) return false;
		 SimuladoHasTurmaId castOther = ( SimuladoHasTurmaId ) other; 
         
		 return (this.getSimuladoIdSimulado()==castOther.getSimuladoIdSimulado())
 && (this.getTurmaIdTurma()==castOther.getTurmaIdTurma())
 && (this.getTurmaIdDisciplina()==castOther.getTurmaIdDisciplina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSimuladoIdSimulado();
         result = 37 * result + this.getTurmaIdTurma();
         result = 37 * result + this.getTurmaIdDisciplina();
         return result;
   }   


}


