package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * SubdisciplinaId generated by hbm2java
 */
@Embeddable
public class SubdisciplinaId  implements java.io.Serializable {


     private int idSubdisciplina;
     private int idDisciplina;

    public SubdisciplinaId() {
    }

    public SubdisciplinaId(int idSubdisciplina, int idDisciplina) {
       this.idSubdisciplina = idSubdisciplina;
       this.idDisciplina = idDisciplina;
    }
   


    @Column(name="idSubdisciplina", nullable=false)
    public int getIdSubdisciplina() {
        return this.idSubdisciplina;
    }
    
    public void setIdSubdisciplina(int idSubdisciplina) {
        this.idSubdisciplina = idSubdisciplina;
    }


    @Column(name="idDisciplina", nullable=false)
    public int getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(int idDisciplina) {
        this.idDisciplina = idDisciplina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof SubdisciplinaId) ) return false;
		 SubdisciplinaId castOther = ( SubdisciplinaId ) other; 
         
		 return (this.getIdSubdisciplina()==castOther.getIdSubdisciplina())
 && (this.getIdDisciplina()==castOther.getIdDisciplina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdSubdisciplina();
         result = 37 * result + this.getIdDisciplina();
         return result;
   }   


}


