package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Subdisciplina generated by hbm2java
 */
@Entity
@Table(name="subdisciplina"
    ,catalog="sgeda"
)
public class Subdisciplina  implements java.io.Serializable {


     private SubdisciplinaId id;
     private Disciplina disciplina;
     private String nome;
     private String descricao;
     private Set questaos = new HashSet(0);

    public Subdisciplina() {
    }

	
    public Subdisciplina(SubdisciplinaId id, Disciplina disciplina) {
        this.id = id;
        this.disciplina = disciplina;
    }
    public Subdisciplina(SubdisciplinaId id, Disciplina disciplina, String nome, String descricao, Set questaos) {
       this.id = id;
       this.disciplina = disciplina;
       this.nome = nome;
       this.descricao = descricao;
       this.questaos = questaos;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idSubdisciplina", column=@Column(name="idSubdisciplina", nullable=false) ), 
        @AttributeOverride(name="idDisciplina", column=@Column(name="idDisciplina", nullable=false) ) } )
    public SubdisciplinaId getId() {
        return this.id;
    }
    
    public void setId(SubdisciplinaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDisciplina", nullable=false, insertable=false, updatable=false)
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }

    
    @Column(name="nome", length=45)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="subdisciplina")
    public Set getQuestaos() {
        return this.questaos;
    }
    
    public void setQuestaos(Set questaos) {
        this.questaos = questaos;
    }




}


