package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Telefone generated by hbm2java
 */
@Entity
@Table(name="telefone"
    ,catalog="sgeda"
)
public class Telefone  implements java.io.Serializable {


     private TelefoneId id;
     private Pessoa pessoa;
     private String ddd;
     private String numero;
     private String descricao;

    public Telefone() {
    }

    public Telefone(TelefoneId id, Pessoa pessoa, String ddd, String numero, String descricao) {
       this.id = id;
       this.pessoa = pessoa;
       this.ddd = ddd;
       this.numero = numero;
       this.descricao = descricao;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTelefone", column=@Column(name="idTelefone", nullable=false) ), 
        @AttributeOverride(name="idPessoa", column=@Column(name="idPessoa", nullable=false) ) } )
    public TelefoneId getId() {
        return this.id;
    }
    
    public void setId(TelefoneId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idPessoa", nullable=false, insertable=false, updatable=false)
    public Pessoa getPessoa() {
        return this.pessoa;
    }
    
    public void setPessoa(Pessoa pessoa) {
        this.pessoa = pessoa;
    }

    
    @Column(name="ddd", nullable=false, length=2)
    public String getDdd() {
        return this.ddd;
    }
    
    public void setDdd(String ddd) {
        this.ddd = ddd;
    }

    
    @Column(name="numero", nullable=false, length=9)
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    
    @Column(name="descricao", nullable=false, length=50)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }




}


