package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TurmaAlunoId generated by hbm2java
 */
@Embeddable
public class TurmaAlunoId  implements java.io.Serializable {


     private int alunoIdAluno;
     private int turmaIdTurma;

    public TurmaAlunoId() {
    }

    public TurmaAlunoId(int alunoIdAluno, int turmaIdTurma) {
       this.alunoIdAluno = alunoIdAluno;
       this.turmaIdTurma = turmaIdTurma;
    }
   


    @Column(name="aluno_idAluno", nullable=false)
    public int getAlunoIdAluno() {
        return this.alunoIdAluno;
    }
    
    public void setAlunoIdAluno(int alunoIdAluno) {
        this.alunoIdAluno = alunoIdAluno;
    }


    @Column(name="turma_idTurma", nullable=false)
    public int getTurmaIdTurma() {
        return this.turmaIdTurma;
    }
    
    public void setTurmaIdTurma(int turmaIdTurma) {
        this.turmaIdTurma = turmaIdTurma;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaAlunoId) ) return false;
		 TurmaAlunoId castOther = ( TurmaAlunoId ) other; 
         
		 return (this.getAlunoIdAluno()==castOther.getAlunoIdAluno())
 && (this.getTurmaIdTurma()==castOther.getTurmaIdTurma());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getAlunoIdAluno();
         result = 37 * result + this.getTurmaIdTurma();
         return result;
   }   


}


