package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Turma generated by hbm2java
 */
@Entity
@Table(name="turma"
    ,catalog="sgeda"
)
public class Turma  implements java.io.Serializable {


     private TurmaId id;
     private Disciplina disciplina;
     private Professor professor;
     private String nome;
     private String descricao;
     private Date dataInicio;
     private Date dataFim;
     private String turno;
     private Set<SimuladoHasTurma> simuladoHasTurmas;
     private Set<AlunoHasTurma> alunoHasTurmas;

    public Turma() {
    }

	
    public Turma(TurmaId id, Disciplina disciplina, Professor professor) {
        this.id = id;
        this.disciplina = disciplina;
        this.professor = professor;
    }
    public Turma(TurmaId id, Disciplina disciplina, Professor professor, String nome, String descricao, Date dataInicio, Date dataFim, String turno, Set simuladoHasTurmas, Set alunoHasTurmas) {
       this.id = id;
       this.disciplina = disciplina;
       this.professor = professor;
       this.nome = nome;
       this.descricao = descricao;
       this.dataInicio = dataInicio;
       this.dataFim = dataFim;
       this.turno = turno;
       this.simuladoHasTurmas = simuladoHasTurmas;
       this.alunoHasTurmas = alunoHasTurmas;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="idTurma", column=@Column(name="idTurma", nullable=false) ), 
        @AttributeOverride(name="idDisciplina", column=@Column(name="idDisciplina", nullable=false) ) } )
    public TurmaId getId() {
        return this.id;
    }
    
    public void setId(TurmaId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idDisciplina", nullable=false, insertable=false, updatable=false)
    public Disciplina getDisciplina() {
        return this.disciplina;
    }
    
    public void setDisciplina(Disciplina disciplina) {
        this.disciplina = disciplina;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idProfessor", nullable=false)
    public Professor getProfessor() {
        return this.professor;
    }
    
    public void setProfessor(Professor professor) {
        this.professor = professor;
    }

    
    @Column(name="nome")
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataInicio", length=19)
    public Date getDataInicio() {
        return this.dataInicio;
    }
    
    public void setDataInicio(Date dataInicio) {
        this.dataInicio = dataInicio;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataFim", length=19)
    public Date getDataFim() {
        return this.dataFim;
    }
    
    public void setDataFim(Date dataFim) {
        this.dataFim = dataFim;
    }

    
    @Column(name="turno", length=50)
    public String getTurno() {
        return this.turno;
    }
    
    public void setTurno(String turno) {
        this.turno = turno;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="turma")
    public Set<SimuladoHasTurma> getSimuladoHasTurmas() {
        return this.simuladoHasTurmas;
    }
    
    public void setSimuladoHasTurmas(Set<SimuladoHasTurma> simuladoHasTurmas) {
        this.simuladoHasTurmas = simuladoHasTurmas;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="turma")
    public Set<AlunoHasTurma> getAlunoHasTurmas() {
        return this.alunoHasTurmas;
    }
    
    public void setAlunoHasTurmas(Set<AlunoHasTurma> alunoHasTurmas) {
        this.alunoHasTurmas = alunoHasTurmas;
    }




}


