package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TurmaSimuladoId generated by hbm2java
 */
@Embeddable
public class TurmaSimuladoId  implements java.io.Serializable {


     private int simuladoIdSimulado;
     private int turmaIdTurma;

    public TurmaSimuladoId() {
    }

    public TurmaSimuladoId(int simuladoIdSimulado, int turmaIdTurma) {
       this.simuladoIdSimulado = simuladoIdSimulado;
       this.turmaIdTurma = turmaIdTurma;
    }
   


    @Column(name="simulado_idSimulado", nullable=false)
    public int getSimuladoIdSimulado() {
        return this.simuladoIdSimulado;
    }
    
    public void setSimuladoIdSimulado(int simuladoIdSimulado) {
        this.simuladoIdSimulado = simuladoIdSimulado;
    }


    @Column(name="turma_idTurma", nullable=false)
    public int getTurmaIdTurma() {
        return this.turmaIdTurma;
    }
    
    public void setTurmaIdTurma(int turmaIdTurma) {
        this.turmaIdTurma = turmaIdTurma;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaSimuladoId) ) return false;
		 TurmaSimuladoId castOther = ( TurmaSimuladoId ) other; 
         
		 return (this.getSimuladoIdSimulado()==castOther.getSimuladoIdSimulado())
 && (this.getTurmaIdTurma()==castOther.getTurmaIdTurma());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getSimuladoIdSimulado();
         result = 37 * result + this.getTurmaIdTurma();
         return result;
   }   


}


