package entidade;
// Generated 09/09/2016 09:36:48 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TurmaAluno generated by hbm2java
 */
@Entity
@Table(name="turma_aluno"
    ,catalog="sgeda"
)
public class TurmaAluno  implements java.io.Serializable {


     private TurmaAlunoId id;
     private Aluno aluno;
     private Turma turma;
     private Date dataIncricao;
     private Boolean aprovado;

    public TurmaAluno() {
    }

	
    public TurmaAluno(TurmaAlunoId id, Aluno aluno, Turma turma) {
        this.id = id;
        this.aluno = aluno;
        this.turma = turma;
    }
    public TurmaAluno(TurmaAlunoId id, Aluno aluno, Turma turma, Date dataIncricao, Boolean aprovado) {
       this.id = id;
       this.aluno = aluno;
       this.turma = turma;
       this.dataIncricao = dataIncricao;
       this.aprovado = aprovado;
    }
   
     @EmbeddedId

    
    @AttributeOverrides( {
        @AttributeOverride(name="alunoIdAluno", column=@Column(name="aluno_idAluno", nullable=false) ), 
        @AttributeOverride(name="turmaIdTurma", column=@Column(name="turma_idTurma", nullable=false) ) } )
    public TurmaAlunoId getId() {
        return this.id;
    }
    
    public void setId(TurmaAlunoId id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="aluno_idAluno", nullable=false, insertable=false, updatable=false)
    public Aluno getAluno() {
        return this.aluno;
    }
    
    public void setAluno(Aluno aluno) {
        this.aluno = aluno;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="turma_idTurma", nullable=false, insertable=false, updatable=false)
    public Turma getTurma() {
        return this.turma;
    }
    
    public void setTurma(Turma turma) {
        this.turma = turma;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="dataIncricao", length=19)
    public Date getDataIncricao() {
        return this.dataIncricao;
    }
    
    public void setDataIncricao(Date dataIncricao) {
        this.dataIncricao = dataIncricao;
    }

    
    @Column(name="aprovado")
    public Boolean getAprovado() {
        return this.aprovado;
    }
    
    public void setAprovado(Boolean aprovado) {
        this.aprovado = aprovado;
    }

}


