package entidade;
// Generated 22/08/2016 17:01:00 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * TurmaId generated by hbm2java
 */
@Embeddable
public class TurmaId  implements java.io.Serializable {


     private int idTurma;
     private int idDisciplina;

    public TurmaId() {
    }

    public TurmaId(int idTurma, int idDisciplina) {
       this.idTurma = idTurma;
       this.idDisciplina = idDisciplina;
    }
   


    @Column(name="idTurma", nullable=false)
    public int getIdTurma() {
        return this.idTurma;
    }
    
    public void setIdTurma(int idTurma) {
        this.idTurma = idTurma;
    }


    @Column(name="idDisciplina", nullable=false)
    public int getIdDisciplina() {
        return this.idDisciplina;
    }
    
    public void setIdDisciplina(int idDisciplina) {
        this.idDisciplina = idDisciplina;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof TurmaId) ) return false;
		 TurmaId castOther = ( TurmaId ) other; 
         
		 return (this.getIdTurma()==castOther.getIdTurma())
 && (this.getIdDisciplina()==castOther.getIdDisciplina());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdTurma();
         result = 37 * result + this.getIdDisciplina();
         return result;
   }   


}


